# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [2]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [ ]:
A = np.arange(1, 16).reshape(3,5)
print(A)

In [ ]:
#Antal "axes"
print(A.ndim)

#Hur matrisen ser ut, dvs 3x5
print(A.shape)

#Hur många element som finns i matrisen
print(A.size)

#Vilken datatyp det är, int32 i detta fallet då
print(A.dtype)

### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [ ]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2
#print(B)
#print(C)
#print(type(B))
#print(type(C))
print(np.subtract(B, C))
print(np.multiply(B, C))

print(B @ C)

### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [ ]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

In [ ]:

#np.exp tar alltså första elementet i matrisen och höjer upp den med basen e
# dvs, e^1, e^2, e^3 etc.
print("Använder basen e på varje element i matrisen: ", np.exp(B), "\n")

#Hittar mionsta värdet i HELA matrisen
print("Printar minsta värdet i hela matrisen: ", B.min(), "\n")

#Kalylerar minsta värdet i varje rad
print("Printar minsta värdet för varje rad i matrisen: ",B.min(axis=1), "\n")

#Kalkylerar minsta värdet i varje column
print("Printar minsta värdet i varje kolumn: ", B.min(axis=0), "\n")

print("Printar index-värdet för det minsta elementet i hela matrisen :", B.argmin(), "\n")
print("Printar index-värdet för det minsta elementet i rad :", B.argmin(axis=1), "\n")

print("Printar summan för alla element: ", B.sum(), "\n")
print("Printar medelvärdet för varje kolumn: ", B.mean(axis=0), "\n")
print("Printar medianen för varje kolumn: ", np.median(B, axis=0), "\n")

### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [ ]:
print(A)

In [ ]:
A[1]

**Answer:**

In [ ]:
#Jag tar endast ut "index" [1] när jag skriver A[1]. A[0] är 1-5, A[3] är 11-15

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [ ]:
A

In [ ]:
for i in A:
    print(i)

In [ ]:
for i in np.nditer(A):
    print(i, end= " ")

### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [ ]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

print(b.shape)

In [ ]:
#a = 1D array och 3 axes = b = 3D array med 2x3x5 shape

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [ ]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

print(m1.shape)
print(m2.shape)

### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [ ]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

In [ ]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b, "\n")



print(A+b)

# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [ ]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print(B)
print(C)
print(D)
print(E)

**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [ ]:
def add_mult_matrices(mat1, mat2, add_multi):
    
        if not (isinstance(mat1, np.ndarray) and isinstance (mat2, np.ndarray)):
            raise Exception("We need matrixes. ")
        
        if add_multi == "add":
                if not mat1.shape == mat2.shape:
                    print("Not Defined")
                else:
                    return mat1 + mat2
        elif add_multi == "multiply":
            if not mat1.shape[1] == mat2.shape[0]:
                print("Not Defined")
            else:
                return mat1 @ mat2
        elif add_multi != "add" and add_multi != "multiply":
            return "Choose either add or multiply"

        


In [ ]:
#B-2A
print(add_mult_matrices(B, -2*A, "add"))

#testade så att if not isinstance fungerade.
#print(add_mult_matrices(32, 18, "add"))


In [ ]:
#3C-E (ska bli ej definierad)
print(add_mult_matrices(3*C, -E, "add"))

In [ ]:
#AC (ska bli ej definierad)
print(add_mult_matrices(A, C, "multiply"))

In [ ]:
#CD
print(add_mult_matrices(C, D, "multiply"))

In [ ]:
#CB
print(add_mult_matrices(C, B, "multiply"))

**Chap2. Question 2**


In [ ]:
Aa = np.array([[1, 2], [2, 4]])
Bb = np.array([[2, 1], [1, 3]])
Cc = np.array([[4, 3], [0, 2]])

In [ ]:
AB = add_mult_matrices(Aa, Bb, "multiply")
AC = add_mult_matrices(Aa, Cc, "multiply")

print("Är Matris AB = AC? :", "\n", AB == AC, "\n")

print("Är Matris B != C? : ", "\n",  Bb != Cc)

In [ ]:
print("AB:", "\n", AB, "\n")

print("AC:", "\n", AC, "\n")

**Chap2. Question 3**

In [ ]:
Aaa = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 4]])
Ddd = np.array([[2, 0, 0], [0, 3, 0], [0, 0, 4]])

In [ ]:
AaaDdd = (add_mult_matrices(Aaa, Ddd, "multiply"))
DddAaa = (add_mult_matrices(Ddd, Aaa, "multiply"))

print("AD:", "\n", AaaDdd, "\n")
print("DA:", "\n", DddAaa, "\n")

**Quiz p.11, Question 2**

In [ ]:
Q1 = np.array([[1, -1], [-1, 1]])
Q2 = np.array([[-1, 1], [1, -1]])

In [ ]:
Q1Q2 = (add_mult_matrices(Q1, Q2, "multiply"))
print("Q1Q2: ", "\n", Q1Q2, "\n")

#Svar: A, på Quiz uppg2

**Chap 6. Question 1**

In [ ]:
I1 = np.array([[5, 6], [4, 5]])
I2 = np.array([[6, 4], [3, 3]])

In [ ]:
Invers_one = (np.linalg.inv(I1))
Invers_two = (np.linalg.inv(I2))

print("Första inversen till array är: ", "\n", Invers_one, "\n")

print("Andra inversen till array är: ", "\n", Invers_two,"\n")

In [ ]:
#Kontroll om inversen gånger matrisen blir identitetsmatrisen
#dvs [1, 0] [0, 1]

#Det blir rätt men tredje kvadranten är ej avrundad
print("Multiplikation av inversen med dens orginalmatris: ", "\n", I1 @ Invers_one, "\n")

Rounded_matris = np.round(I1 @ Invers_one)

print("Avrundad identitetsmatris: ","\n", Rounded_matris, "\n")

In [ ]:
#Kontroll om inversen gånger matrisen blir identitetsmatrisen
#dvs [1, 0] [0, 1]

#Det blir rätt men tredje kvadranten är ej avrundad
print("Multiplikation av inversen med dens orginalmatris: ", "\n", I2 @ Invers_two, "\n")


#Behöver ej avrunda denna
#Rounded_matris2 = np.round(I2 @ Invers_two)

#print("Avrundad identitetsmatris: ","\n", Rounded_matris2, "\n")

**Quiz p.19, Question 3**

In [ ]:
I3 = np.array([[2, 2], [1, 2]])

I3_invers = np.linalg.inv(I3)

EQ1 = np.array([[2, -2], [-1, 2]])
EQ2 = np.array([[-2, 2], [1, -2]])
EQ3 = np.array([[2, 2], [-1, -2]])
EQ4 = np.array([[-2, -2], [1, 2]])


In [ ]:
print(((1/2)*EQ1 == I3_invers).all())

print(((1/2)*EQ2 == I3_invers).all())

print(((1/2)*EQ3 == I3_invers).all())

print(((1/2)*EQ4 == I3_invers).all())


#Svaret blir alltså A)

**Chap10. Question 1 a)**

In [ ]:
A = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
b_arrow = np.array([-7, 5, 2])


In [ ]:
# linjär-algebra solver som finns inbyggt i numpy
x = np.linalg.solve(A, b_arrow)
print(x)

In [ ]:
# kollar om A gånger x blir b_arrow
(A @ x == b_arrow).all()

**Chap10. Question 1 b)**

In [ ]:
A1 = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]])
b_arrow1 = np.array([1, -1, 1])

In [ ]:
# linjär-algebra solver som finns inbyggt i numpy
x1 = np.linalg.solve(A1, b_arrow1)
print(x)

In [ ]:
# Double check if Ax = b.
(A1 @ x1 == b_arrow1).all()

**Chap 12. Question 1**

In [ ]:
L12 = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])

In [ ]:
L12_inverse = np.linalg.inv(L12)


In [ ]:
#Kontroll så att inversen * matrisen blir Identitetsmatrisen
np.round(L12 @ L12_inverse)

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [10]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [11]:
# The base attribute of a view returns the original array while it returns None for a copy.

print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [12]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [ ]:
#v1 är en kopia och v2 är en view, detta ser vi m.h.a .base
#ändrar man på "view" så ändras även copyn. 
#Eftersom båda delar samma data så gör valfri modifiering ändring i båda